# Generated by Django 5.2.14 on 2026-05-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('display_name', models.CharField(max_length=64)),
                ('provider_type', models.CharField(choices=[('cloud', 'Cloud'), ('on_prem', 'On-premises')], max_length=16)),
                ('data_source_tier', models.CharField(choices=[('realtime_api', 'Tier 1 — real-time machine-readable API'), ('scraped_page', 'Tier 2 — HTML/page scraping'), ('manual_curation', 'Tier 3 — gated; YAML curation + override'), ('synthetic', 'On-prem / reserved-cloud generator output')], max_length=24)),
                ('pricing_url', models.URLField(blank=True)),
                ('has_api', models.BooleanField(default=False)),
                ('api_endpoint', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('provider_type', 'slug'),
            },
        ),
    ]
