# Generated by Django 5.2.14 on 2026-05-18 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_benchmark_point'),
        ('pricing', '0001_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(max_length=64)),
                ('region', models.CharField(blank=True, max_length=64)),
                ('hourly_usd', models.DecimalField(decimal_places=4, max_digits=8)),
                ('available', models.BooleanField(default=True)),
                ('scraped_at', models.DateTimeField(db_index=True)),
                ('raw_payload', models.JSONField()),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.gpu')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pricing.provider')),
            ],
            options={
                'ordering': ('-scraped_at',),
                'indexes': [models.Index(fields=['provider', 'gpu', 'tier', '-scraped_at'], name='pricing_pri_provide_c6aaaf_idx')],
            },
        ),
    ]
