# Generated by Django 5.2.14 on 2026-05-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_benchmark_point'),
        ('pricing', '0003_timescaledb'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pricingsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('hourly_usd__gte', 0)), name='pricingsnapshot_hourly_usd_nonneg'),
        ),
    ]
