# Generated by Django 5.2.14 on 2026-05-21 21:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_benchmark_point'),
        ('pricing', '0006_continuous_aggregate_and_retention'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('display_name', models.CharField(max_length=128)),
                ('vendor', models.CharField(max_length=64)),
                ('num_gpus', models.PositiveSmallIntegerField()),
                ('cpu_model', models.CharField(max_length=128)),
                ('cpu_sockets', models.PositiveSmallIntegerField()),
                ('ram_gb', models.PositiveIntegerField()),
                ('nvme_tb', models.PositiveIntegerField()),
                ('network_gbps', models.PositiveIntegerField()),
                ('host_tdp_watts', models.PositiveIntegerField(help_text='non-GPU power draw at peak')),
                ('reference_msrp_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.gpu')),
            ],
            options={
                'ordering': ('vendor', 'slug'),
            },
        ),
        migrations.CreateModel(
            name='OnPremDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('display_name', models.CharField(max_length=128)),
                ('num_nodes', models.PositiveIntegerField(default=1)),
                ('capex_per_node_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salvage_pct', models.DecimalField(decimal_places=3, default=Decimal('0.100'), max_digits=4)),
                ('depreciation_years', models.PositiveSmallIntegerField(default=4)),
                ('expected_utilization_pct', models.DecimalField(decimal_places=3, default=Decimal('0.700'), max_digits=4)),
                ('power_usd_per_kwh', models.DecimalField(decimal_places=4, max_digits=6)),
                ('pue', models.DecimalField(decimal_places=3, default=Decimal('1.400'), max_digits=4)),
                ('monthly_colo_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('monthly_bandwidth_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('sysadmin_annual_burdened_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gpu_count_per_admin', models.PositiveIntegerField(default=128)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hardware_sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pricing.hardwaresku')),
            ],
            options={
                'ordering': ('slug',),
            },
        ),
    ]
