# Generated by Django 5.2.14 on 2026-05-23 04:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_benchmark_point'),
        ('pricing', '0007_hardware_sku_and_on_prem_deployment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedCapacityProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('display_name', models.CharField(max_length=128)),
                ('gpus_per_node', models.PositiveSmallIntegerField()),
                ('payment_cadence', models.CharField(choices=[('all_upfront', 'All Upfront'), ('partial_upfront', 'Partial Upfront'), ('no_upfront', 'No Upfront'), ('capacity_block', 'Capacity Block')], max_length=16)),
                ('term_months', models.PositiveSmallIntegerField()),
                ('upfront_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('monthly_recurring_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('per_active_hour_usd', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8)),
                ('capacity_block_total_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('minimum_utilization_floor_pct', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=4)),
                ('on_demand_reference_usd_per_hour', models.DecimalField(blank=True, decimal_places=4, help_text='display-only; never used in math', max_digits=8, null=True)),
                ('listing_observed_at', models.DateField(help_text="when this product's pricing was last verified")),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cloud_provider', models.ForeignKey(limit_choices_to={'provider_type': 'cloud'}, on_delete=django.db.models.deletion.PROTECT, to='pricing.provider')),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.gpu')),
            ],
            options={
                'ordering': ('cloud_provider__slug', 'term_months', 'slug'),
            },
        ),
    ]
