# Generated by Django 5.2.14 on 2026-05-23 04:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0008_reserved_capacity_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedCloudDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('display_name', models.CharField(max_length=128)),
                ('region', models.CharField(blank=True, max_length=64)),
                ('num_nodes', models.PositiveIntegerField(default=1)),
                ('expected_utilization_pct', models.DecimalField(decimal_places=3, default=Decimal('0.700'), max_digits=4)),
                ('upfront_override_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monthly_recurring_override_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('per_hour_override_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cloud_provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pricing.provider')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pricing.reservedcapacityproduct')),
            ],
            options={
                'ordering': ('slug',),
            },
        ),
    ]
