# Generated by Django 5.2.14 on 2026-05-23 11:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0009_reserved_cloud_deployment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedcapacityproduct',
            name='block_duration_hours',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Actual block duration in hours for capacity_block cadence (e.g. 336 for 14d). Ignored for other cadences.', null=True),
        ),
        migrations.AlterField(
            model_name='reservedclouddeployment',
            name='expected_utilization_pct',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.700'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.001')), django.core.validators.MaxValueValidator(Decimal('1.000'))]),
        ),
    ]
