# Generated by Django 5.2.14 on 2026-05-23 11:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0010_add_block_duration_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservedcapacityproduct',
            name='minimum_utilization_floor_pct',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.000')), django.core.validators.MaxValueValidator(Decimal('1.000'))]),
        ),
    ]
