# Generated by Django 5.2.14 on 2026-05-23 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_benchmark_point'),
        ('pricing', '0012_add_nonneg_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservedcapacityproduct',
            name='gpus_per_node',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='reservedcapacityproduct',
            name='term_months',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='reservedcapacityproduct',
            constraint=models.CheckConstraint(condition=models.Q(('gpus_per_node__gte', 1)), name='reservedcapacityproduct_gpus_per_node_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='reservedcapacityproduct',
            constraint=models.CheckConstraint(condition=models.Q(('term_months__gte', 1)), name='reservedcapacityproduct_term_months_gte_1'),
        ),
    ]
