# Generated by Django 5.2.14 on 2026-05-23 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0013_add_gpus_term_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservedcapacityproduct',
            name='block_duration_hours',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Actual block duration in hours for capacity_block cadence (e.g. 336 for 14d). Ignored for other cadences.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
