# Generated by Django 5.2.14 on 2026-05-23 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_benchmark_point'),
        ('pricing', '0014_alter_reservedcapacityproduct_block_duration_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingDriftAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(max_length=256)),
                ('curated_usd_per_hour', models.DecimalField(decimal_places=4, max_digits=8)),
                ('observed_usd_per_hour', models.DecimalField(decimal_places=4, max_digits=8)),
                ('drift_pct', models.DecimalField(decimal_places=3, max_digits=8)),
                ('source_url', models.URLField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=10)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.gpu')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pricing.provider')),
            ],
            options={
                'ordering': ('-detected_at',),
                'indexes': [models.Index(fields=['acknowledged_at', '-detected_at'], name='pricing_pri_acknowl_ec6cae_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('drift_pct__gte', 0)), name='pricingdriftalert_drift_pct_nonneg'), models.CheckConstraint(condition=models.Q(('curated_usd_per_hour__gte', 0)), name='pricingdriftalert_curated_usd_per_hour_nonneg'), models.CheckConstraint(condition=models.Q(('observed_usd_per_hour__gte', 0)), name='pricingdriftalert_observed_usd_per_hour_nonneg')],
            },
        ),
    ]
