# Generated by Django 5.2.14 on 2026-05-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0015_pricing_drift_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingdriftalert',
            name='tier',
            field=models.CharField(max_length=128),
        ),
    ]
