# Generated by Django 5.2.14 on 2026-05-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0016_expand_current_cost_cells'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentCostCell',
            fields=[
                ('row_hash', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('gpu_slug', models.CharField(max_length=64)),
                ('gpu_display_name', models.CharField(max_length=128)),
                ('model_slug', models.CharField(max_length=64)),
                ('model_display_name', models.CharField(max_length=128)),
                ('quantization_slug', models.CharField(max_length=64)),
                ('tp_size', models.PositiveIntegerField()),
                ('batch_size', models.PositiveIntegerField()),
                ('context_length', models.PositiveIntegerField()),
                ('provider_slug', models.CharField(max_length=64)),
                ('provider_display_name', models.CharField(max_length=64)),
                ('provider_type', models.CharField(max_length=16)),
                ('data_source_tier', models.CharField(max_length=24)),
                ('tier', models.CharField(max_length=64)),
                ('region', models.CharField(blank=True, max_length=64, null=True)),
                ('hourly_usd', models.DecimalField(decimal_places=4, max_digits=12)),
                ('decode_tps_aggregate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prefill_tps_aggregate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ttft_ms', models.FloatField(null=True)),
                ('usd_per_m_input', models.DecimalField(decimal_places=4, max_digits=12)),
                ('usd_per_m_output', models.DecimalField(decimal_places=4, max_digits=12)),
                ('scraped_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'pricing_current_cost_cells',
                'managed': False,
            },
        ),
    ]
