# Generated by Django 5.2.14 on 2026-05-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0016_alter_pricingdriftalert_tier_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingdriftalert',
            name='tier',
            field=models.CharField(max_length=256),
        ),
    ]
