# Generated by Django 5.2.14 on 2026-05-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GPU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("display_name", models.CharField(max_length=128)),
                (
                    "vendor",
                    models.CharField(
                        choices=[("nvidia", "NVIDIA"), ("amd", "AMD")], max_length=16
                    ),
                ),
                ("architecture", models.CharField(max_length=32)),
                ("vram_gb", models.PositiveIntegerField()),
                ("memory_bandwidth_gbs", models.PositiveIntegerField()),
                ("fp16_tflops", models.FloatField()),
                ("fp8_tflops", models.FloatField(blank=True, null=True)),
                ("int8_tops", models.FloatField(blank=True, null=True)),
                ("tdp_watts", models.PositiveIntegerField()),
                ("interconnect", models.CharField(max_length=32)),
                (
                    "nvlink_bandwidth_gbs",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("supports_fp8_native", models.BooleanField(default=False)),
                ("supports_fp4_native", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("vendor", "slug"),
            },
        ),
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "ordering": ("pk",),
            },
        ),
        migrations.CreateModel(
            name="Quantization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("display_name", models.CharField(max_length=64)),
                ("weight_bits", models.FloatField()),
                ("kv_cache_bits", models.FloatField()),
                ("requires_nvidia_arch", models.JSONField(blank=True, default=list)),
                ("requires_amd_arch", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("weight_bits",),
            },
        ),
    ]
