# Generated by Django 5.2.14 on 2026-05-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quantization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("display_name", models.CharField(max_length=64)),
                ("weight_bits", models.FloatField()),
                ("kv_cache_bits", models.FloatField()),
                ("requires_nvidia_arch", models.JSONField(blank=True, default=list)),
                ("requires_amd_arch", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("weight_bits",),
            },
        ),
    ]
