# Generated by Django 5.2.14 on 2026-05-18 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GPU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("display_name", models.CharField(max_length=128)),
                (
                    "vendor",
                    models.CharField(
                        choices=[("nvidia", "NVIDIA"), ("amd", "AMD")], max_length=16
                    ),
                ),
                ("architecture", models.CharField(max_length=32)),
                ("vram_gb", models.PositiveIntegerField()),
                ("memory_bandwidth_gbs", models.PositiveIntegerField()),
                ("fp16_tflops", models.FloatField()),
                ("fp8_tflops", models.FloatField(blank=True, null=True)),
                ("int8_tops", models.FloatField(blank=True, null=True)),
                ("tdp_watts", models.PositiveIntegerField()),
                ("interconnect", models.CharField(max_length=32)),
                (
                    "nvlink_bandwidth_gbs",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("supports_fp8_native", models.BooleanField(default=False)),
                ("supports_fp4_native", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("vendor", "slug"),
            },
        ),
        migrations.CreateModel(
            name="Quantization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("display_name", models.CharField(max_length=64)),
                ("weight_bits", models.FloatField()),
                ("kv_cache_bits", models.FloatField()),
                ("requires_nvidia_arch", models.JSONField(blank=True, default=list)),
                ("requires_amd_arch", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("weight_bits",),
            },
        ),
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=128, unique=True)),
                ("display_name", models.CharField(max_length=128)),
                ("family", models.CharField(max_length=64)),
                (
                    "architecture",
                    models.CharField(
                        choices=[("dense", "Dense"), ("moe", "Mixture of Experts")],
                        max_length=16,
                    ),
                ),
                ("total_params_b", models.FloatField()),
                ("active_params_b", models.FloatField()),
                ("num_layers", models.PositiveIntegerField()),
                ("num_attention_heads", models.PositiveIntegerField()),
                ("num_kv_heads", models.PositiveIntegerField()),
                ("head_dim", models.PositiveIntegerField()),
                ("max_context", models.PositiveIntegerField()),
                ("hf_repo", models.CharField(max_length=128)),
                ("license", models.CharField(max_length=64)),
                ("is_coding_specialist", models.BooleanField(default=False)),
                ("recommended_tp", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommended_quant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.quantization",
                    ),
                ),
            ],
            options={
                "ordering": ("family", "slug"),
            },
        ),
    ]
